
services:
  postgres:
    container_name: my-manager-banco
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: product
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'  # Porta PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped


    
  
 
volumes:
  postgres-data:

