
services:
  postgres:
    container_name: my-managerddd
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: product
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'  # Porta PostgreSQL
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: my-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: talita@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050  # Porta pgAdmin correta
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - '5050:5050'  # Porta de acesso ao pgAdmin
    restart: unless-stopped

      
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    
  
 
volumes:
  postgres-data:
  pgadmin-data:
